
[functions.azure-tts]
enabled = true
verify_jwt = false
import_map = "./functions/azure-tts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/azure-tts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/azure-tts/*.html" ]

[functions.asr-eval]
enabled = true
verify_jwt = false
import_map = "./functions/asr-eval/deno.json"
entrypoint = "./functions/asr-eval/index.ts"
